config/routes.rb
Rails.application.routes.draw do
  resources :animes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get '/search', to: 'animes#search'
  get "/anime_posters", to: 'animes#_anime_posters'
  root to: "home_page#index"
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/anime.rb
class Anime < ApplicationRecord
    has_and_belongs_to_many :genres
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_and_belongs_to_many :animes
end

app/controllers/animes_controller.rb
class AnimesController < ApplicationController
  before_action :set_anime, only: %i[ show edit update destroy ]

  # GET /animes or /animes.json
  def index
    @genres = Genre.all
  end

  def _anime_posters
    @genres = Genre.all
    selected_genres = params[:genre]&.split(',') || []
    selected_status = params[:status]&.capitalize
    selected_type = params[:type]
    from_year = params[:from]&.to_i
    to_year = params[:to]&.to_i
  
    genre_ids = Genre.where(name: selected_genres).pluck(:id)
    @animes = genre_ids.empty? ? Anime.all : Anime.joins(:genres)
                   .where(genres: { id: genre_ids })
                   .group('animes.id')
                   .having('COUNT(DISTINCT genres.id) = ?', genre_ids.count)
  
    @animes = @animes.where(release_status: selected_status) if selected_status
    @animes = @animes.where(content_type: selected_type) if selected_type
  
    if from_year && to_year
      from_date = Date.new(from_year, 1, 1)
      to_date = Date.new(to_year, 12, 31).end_of_day
      @animes = @animes.where(release_date: from_date..to_date)
    end
  
    @pagy, @animes = pagy(@animes)
  end

  def search
    @query = params[:query]
    @animes = Anime.where("name LIKE :query OR original_name LIKE :query", query: "%#{@query}%")
  end

  # GET /animes/1 or /animes/1.json
  def show
  end

  # GET /animes/new
  def new
    @anime = Anime.new
  end

  # GET /animes/1/edit
  def edit
  end

  # POST /animes or /animes.json
  def create
    @anime = Anime.new(anime_params)

    respond_to do |format|
      if @anime.save
        format.html { redirect_to anime_url(@anime), notice: "Anime was successfully created." }
        format.json { render :show, status: :created, location: @anime }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @anime.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animes/1 or /animes/1.json
  def update
    respond_to do |format|
      if @anime.update(anime_params)
        format.html { redirect_to anime_url(@anime), notice: "Anime was successfully updated." }
        format.json { render :show, status: :ok, location: @anime }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @anime.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animes/1 or /animes/1.json
  def destroy
    @anime.destroy!

    respond_to do |format|
      format.html { redirect_to animes_url, notice: "Anime was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_anime
      @anime = Anime.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def anime_params
      params.require(:anime).permit(:name, :original_name, :description, :poster, :release_date, :type, :total_episodes, :studio, :director, :logo, :horizontal_poster)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pagy::Backend
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
    def index
        @animes = Anime.all
    end
end

app/helpers/animes_helper.rb
module AnimesHelper
    include Pagy::Frontend
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animes/_anime.html.erb
<div id="<%= dom_id anime %>">
  <p>
    <strong>Name:</strong>
    <%= anime.name %>
  </p>

  <p>
    <strong>Original name:</strong>
    <%= anime.original_name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= anime.description %>
  </p>

  

  <p>
    <strong>Release date:</strong>
    <%= anime.release_date %>
  </p>

  <p>
    <strong>Type:</strong>
    <%= anime.content_type %>
  </p>

  <p>
    <strong>Episode number:</strong>
    <%= anime.total_episodes %>
  </p>

  <p>
    <strong>Studio:</strong>
    <%= anime.studio %>
  </p>

  <p>
    <strong>Director:</strong>
    <%= anime.director %>
  </p>


</div>

app/views/animes/_anime_posters.html.erb
<div class = "catalog-grid-wrapper">
    <h2 class = "anime-catalog-title">Каталог аніме</h2>
    <section class="catalog-grid">
        <% unless @animes.nil? %>
        <% @animes.each do |anime| %>
            <%= link_to anime_path(anime) do %>
                <div class="catalog-anime-items">
                    <div>
                        <div class="catalog-anime-posters-wrapper">
                            # <%= image_tag "data:image/jpg;base64,#{Base64.encode64(anime.poster).html_safe}", class: "catalog-anime-posters" %>
                        </div>
                        <h4 class="anime-catalog-names"><%= anime.name %></h4>
                    </div>
                        
                    <div class="catalog-anime-release-wrapper">
                        <span class="catalog-anime-release"><%= anime.content_type %> / <%= anime.release_date.year %></span>
                    </div>
                </div>
            <% end %>
        <% end %>
        <% end %>
    </section>
    <% unless @pagy.nil? %>
        <%== pagy_bootstrap_nav(@pagy, anchor_string: 'data-action="anime#_anime_posters"')%>
    <% end %>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function() { 
        setTimeout(() => {
            const paginationLinks = document.querySelectorAll('.pagination a');
            if (paginationLinks) {
                paginationLinks.forEach(link => {
                    link.addEventListener("click", function(event) {
                        event.preventDefault();
                        const target = event.currentTarget;
                        if (target.href) {
                            fetch(target.href)
                            .then(response => response.text())
                            .then(data => {
                                document.getElementById("anime-posters").innerHTML = data;
                                window.scrollTo(0, 0); // Scroll to the top of the page
                            })
                            .catch(error => console.error('Error:', error));
                        }
                    });
                });
            }    
        }, 3000);
        
    });   
</script>

app/views/animes/_form.html.erb
<%= form_with(model: anime) do |form| %>
  <% if anime.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(anime.errors.count, "error") %> prohibited this anime from being saved:</h2>

      <ul>
        <% anime.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :original_name, style: "display: block" %>
    <%= form.text_field :original_name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :poster, style: "display: block" %>
    <%= form.text_field :poster %>
  </div>

  <div>
    <%= form.label :release_date, style: "display: block" %>
    <%= form.date_field :release_date %>
  </div>

  <div>
    <%= form.label :type, style: "display: block" %>
    <%= form.text_field :type %>
  </div>

  <div>
    <%= form.label :total_episodes, style: "display: block" %>
    <%= form.number_field :total_episodes %>
  </div>

  <div>
    <%= form.label :studio, style: "display: block" %>
    <%= form.text_field :studio %>
  </div>

  <div>
    <%= form.label :director, style: "display: block" %>
    <%= form.text_field :director %>
  </div>

  <div>
    <%= form.label :logo, style: "display: block" %>
    <%= form.text_field :logo %>
  </div>

  <div>
    <%= form.label :horizontal_poster, style: "display: block" %>
    <%= form.text_field :horizontal_poster %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/animes/edit.html.erb
<h1>Editing anime</h1>

<%= render "form", anime: @anime %>

<br>

<div>
  <%= link_to "Show this anime", @anime %> |
  <%= link_to "Back to animes", animes_path %>
</div>

app/views/animes/new.html.erb
<h1>New anime</h1>

<%= render "form", anime: @anime %>

<br>

<div>
  <%= link_to "Back to animes", animes_path %>
</div>

app/views/animes/search.html.erb
<div class = "main-container">
    <div class = "search-result-title-wrapper">
        <h1 class = "search-result-title">Результати пошуку "<%= @query %>"</h1>
    </div>
    <% if @animes.present? %>
        <div class = "search-result-grid-wrapper">
            <section class = "search-result-grid">
                <% @animes.each do |anime| %>
                    <%= link_to anime_path(anime) do %>
                        <div class="search-result-anime-items">
                            <div>
                                <div class="search-result-anime-posters-wrapper">
                                    <%= image_tag "data:image/jpg;base64,#{Base64.encode64(anime.poster).html_safe}", class: "search-result-anime-posters" %>
                                </div>
                                <h4 class="search-result-anime-names"><%= anime.name %></h4>
                            </div>
                        
                            <div class="search-result-anime-release-wrapper">
                                <span class="search-result-anime-release"><%= anime.content_type %> / <%= anime.release_date.year %></span>
                            </div>
                        </div>
                    <% end %>
                <% end %>
            </section>
        </div>
    <% else %>
        <h3 class = "search-no-result-message">Немає результатів для вашого запиту.</h3>
    <% end %>
</div>

app/views/animes/show.html.erb
<div class = "anime-show-page-container">       
    <%= image_tag "data:image/jpg;base64,#{Base64.encode64(@anime.poster).html_safe}", class: "anime-show-background-image"%>    
    <div class = "main-container-anime-show-page">   
        <div class = "anime-show-characteristics-container">
            <div class = "anime-show-poster-wrapper">
                 <%= image_tag "data:image/jpg;base64,#{Base64.encode64(@anime.poster).html_safe}", class: "anime-show-poster"%>  
            </div>
            <div class = "anime-details-container">
                <div class = "anime-show-title-container">
                    <div class ="anime-show-original-name-wrapper">
                        <h3 class = "anime-show-original-name"><%=@anime.original_name %></h3>
                    </div>

                    <div class = "anime-show-name-wrapper">
                        <h1 class = "anime-show-name"><%=@anime.name %></h1>
                        <div class = "anime-show-age-rating-wrapper">
                            <%= image_tag "data:image/jpg;base64,#{Base64.encode64(@anime.age_rating).html_safe}", class: "anime-show-age-rating-image"%> 
                        </div> 
                    </div>
                    
                </div>

                <div class = "genres-container">
                    <%@anime.genres.each do |genre|%>
                    <div class = "genre-buttons">
                        <span class = "genre-buttons-text">
                            <%=genre.name%>
                        </span>
                    </div>
                    <%end%>
                </div>

                <div class = "anime-show-description-wrapper">
                   <span class = "anime-show-description">
                    <%=@anime.description %>
                   </span>
                </div>
            </div>

            <div class = "anime-show-details-values-container">

                 <div class = "anime-show-details-value-container">
                    <div class = "anime-show-details-wrapper">
                        <div class = "anime-show-details-icon-wrapper">
                            <%= image_tag('content-type.png', :class => "anime-show-details-icon")%> 
                        </div>
                        <span class = "anime-show-details-value">
                            <%=@anime.content_type %>
                        </span>
                    </div>
                </div>

                <div class = "anime-show-details-value-container">
                    <div class = "anime-show-details-wrapper">
                        <div class = "anime-show-details-icon-wrapper">
                            <%= image_tag('status.png', :class => "anime-show-details-icon")%> 
                        </div>
                        <span class = "anime-show-details-value">
                            <%=@anime.release_status %>
                        </span>
                    </div>
                </div>

                <div class = "anime-show-details-value-container">
                    <div class = "anime-show-details-wrapper">
                        <div class = "anime-show-details-icon-wrapper">
                            <%= image_tag('episodes.png', :class => "anime-show-details-icon")%> 
                        </div>
                        <span class = "anime-show-details-value">
                           <%=@anime.released_episodes%> / <%=@anime.total_episodes%>
                        </span>
                    </div>
                </div>

                 <div class = "anime-show-details-value-container">
                    <div class = "anime-show-details-wrapper">
                        <div class = "anime-show-details-icon-wrapper">
                            <%= image_tag('calendar.png', :class => "anime-show-details-icon")%> 
                        </div>
                        <span class = "anime-show-details-value">
                            <%=@anime.release_date.year %>
                        </span>
                    </div>
                </div>

                <div class = "anime-show-details-value-container">
                    <div class = "anime-show-details-wrapper">
                        <div class = "anime-show-details-icon-wrapper">
                            <%= image_tag('studio.png', :class => "anime-show-details-icon")%> 
                        </div>
                        <span class = "anime-show-details-value">
                            <%=@anime.studio %>
                        </span>
                    </div>
                </div>

                <div class = "anime-show-details-value-container">
                    <div class = "anime-show-details-wrapper">
                        <div class = "anime-show-details-icon-wrapper">
                            <%= image_tag('director.png', :class => "anime-show-details-icon")%> 
                        </div>
                        <span class = "anime-show-details-value">
                            <%=@anime.director %>
                        </span>
                    </div>
                </div>

            </div>
        </div>
        <div class = "anime-show-trailer-container">
            <h2 class = "anime-show-trailer-title">Трейлер</h2>
            <div class = "anime-show-trailer">
               <iframe width="100%" height="100%" src="<%=@anime.trailer_link%>" frameborder="0" allowfullscreen></iframe> 
            </div>
        </div>
    </div>
</div>

app/views/home_page/_recent_anime_list.html.erb
<div class = "main-container">
    <h2 class = "recent-anime-grid-section-title">Новинки, що набирають популярність</h2>
    <section class = "recent-anime-grid">
        <div class = "recent-anime-grid-items">
            <div class = "recent-anime-grid-poster-wrapper">
                <%= image_tag "data:image/jpg;base64,#{Base64.encode64(@animes[10].horizontal_poster).html_safe}", class: "recent-anime-grid-posters-left"%>
            </div>
            <div class = "recent-anime-grid-description-wrapper-left">
                <div class = "recent-anime-grid-title-wrapper-left">
                    <h1 class = "recent-anime-grid-title-left"><%=@animes[10].name%></h1>
                </div>
                <div class = "recent-anime-description-wrapper-left">
                    <span class = "recent-anime-description-left"><%=@animes[10].description%></span>
                </div>
                <%= button_to "Перейти на сторінку", @animes[10], method: :get, class:"recent-anime-button"%>
            </div>


        </div>

        <div class = "recent-anime-grid-items">
            <div class = "recent-anime-grid-description-wrapper-right">
                <div class = "recent-anime-grid-title-wrapper-right">
                    <h1 class = "recent-anime-grid-title-right"><%=@animes[11].name%></h1>
                </div>
                <div class = "recent-anime-description-wrapper-right">
                    <span class = "recent-anime-description-right"><%=@animes[11].description%></span>
                </div>
               <%= button_to "Перейти на сторінку", @animes[11], method: :get, class:"recent-anime-button"%>
            </div>

            <div class = "recent-anime-grid-poster-wrapper-right">
                <%= image_tag "data:image/jpg;base64,#{Base64.encode64(@animes[11].horizontal_poster).html_safe}", class: "recent-anime-grid-posters-left"%>
            </div>   
        </div>

        <div class = "recent-anime-grid-items">
            <div class = "recent-anime-grid-poster-wrapper-left">
                <%= image_tag "data:image/jpg;base64,#{Base64.encode64(@animes[50].horizontal_poster).html_safe}", class: "recent-anime-grid-posters-left"%>
            </div>

            <div class = "recent-anime-grid-description-wrapper-left">
                <div class = "recent-anime-grid-title-wrapper-left">
                    <h1 class = "recent-anime-grid-title-left"><%=@animes[50].name%></h1>
                </div>
                <div class = "recent-anime-description-wrapper-left">
                    <span class = "recent-anime-description-left"><%=@animes[50].description%></span>
                </div>
                <%= button_to "Перейти на сторінку", @animes[50], method: :get, class:"recent-anime-button"%>
            </div>
        </div>

        <div class = "recent-anime-grid-items">

            <div class = "recent-anime-grid-description-wrapper-right">
                <div class = "recent-anime-grid-title-wrapper-right">
                    <h1 class = "recent-anime-grid-title-right"><%=@animes[51].name%></h1>
                </div>
                <div class = "recent-anime-description-wrapper-right">
                    <span class = "recent-anime-description-right"><%=@animes[51].description%></span>
                </div>
                <%= button_to "Перейти на сторінку", @animes[51], method: :get, class:"recent-anime-button"%>
            </div>

            <div class = "recent-anime-grid-poster-wrapper-right">
                <%= image_tag "data:image/jpg;base64,#{Base64.encode64(@animes[51].horizontal_poster).html_safe}", class: "recent-anime-grid-posters-left"%>
            </div>
            
        </div>

        <div class = "recent-anime-grid-items">
            <div class = "recent-anime-grid-poster-wrapper-left">
               <%= image_tag "data:image/jpg;base64,#{Base64.encode64(@animes[52].horizontal_poster).html_safe}", class: "recent-anime-grid-posters-left"%>
            </div>
            <div class = "recent-anime-grid-description-wrapper-left">
                <div class = "recent-anime-grid-title-wrapper-left">
                    <h1 class = "recent-anime-grid-title-left"><%=@animes[52].name%></h1>
                </div>
                <div class = "recent-anime-description-wrapper-left">
                    <span class = "recent-anime-description-left"><%=@animes[52].description%></span>
                </div>
               <%= button_to "Перейти на сторінку", @animes[52], method: :get, class:"recent-anime-button"%>
            </div>
        </div>
    </section>

    <div class = "go-to-filter-page-container">
        <h3 class = "go-to-filter-page-text">Не знайшли те що Вас цікавить? Перегляьте весь наш каталог.</h3>
        <%= button_to "Перейти", animes_path, method: :get, class: "go-to-filter-page-button"%>
    </div>

</div>

app/views/home_page/_trending_grid.html.erb
<div class = "trending-grid-wrapper">
   <h1 class = "trending-grid-title">Найпопулярніші аніме за останній місяць</h1>
   <section class="trending-grid">
      <%= link_to anime_path(@animes[1]) do %>
         <div class = "trending-anime-items">
            
               <div>
                  <div class = "trending-anime-posters-wrapper">
                     <%= image_tag "data:image/jpg;base64,#{Base64.encode64(@animes[1].poster).html_safe}", class: "trending-anime-posters" %>
                  </div>
                  <h2 class = "trending-anime-title"> <%=@animes[1].name %> </h2>
               </div>

            <div class = "trending-anime-release-wrapper">
               <span class = "trending-anime-release"><%=@animes[1].content_type %> / <%=@animes[1].release_date.year %><span>
            </div>
         </div>
      <%end%>

      <%= link_to anime_path(@animes[2]) do %>
         <div class = "trending-anime-items">
            <div>
               <div class = "trending-anime-posters-wrapper">
                  <%= image_tag "data:image/jpg;base64,#{Base64.encode64(@animes[2].poster).html_safe}", class: "trending-anime-posters" %>
               </div>
               <h2 class = "trending-anime-title"> <%=@animes[2].name %> </h2>
            </div>
            <div class = "trending-anime-release-wrapper">
               <span class = "trending-anime-release"><%=@animes[2].content_type %> / <%=@animes[2].release_date.year %><span>
            </div>
         </div>
      <%end%>

      <%= link_to anime_path(@animes[3]) do %>
         <div class = "trending-anime-items">
            <div>
               <div class = "trending-anime-posters-wrapper">
                  <%= image_tag "data:image/jpg;base64,#{Base64.encode64(@animes[3].poster).html_safe}", class: "trending-anime-posters" %>
               </div>
               <h2 class = "trending-anime-title"> <%=@animes[3].name %> </h2>
            </div>
            <div class = "trending-anime-release-wrapper">
               <span class = "trending-anime-release"><%=@animes[3].content_type %> / <%=@animes[3].release_date.year %><span>
            </div>
         </div>
      <%end%>

      <%= link_to anime_path(@animes[4]) do %>
         <div class = "trending-anime-items">
            <div>
               <div class = "trending-anime-posters-wrapper">
                  <%= image_tag "data:image/jpg;base64,#{Base64.encode64(@animes[4].poster).html_safe}", class: "trending-anime-posters" %>
               </div>
               <h2 class = "trending-anime-title"> <%=@animes[4].name %> </h2>
            </div>
            <div class = "trending-anime-release-wrapper">
               <span class = "trending-anime-release"><%=@animes[4].content_type %> / <%=@animes[4].release_date.year %><span>
            </div>
         </div>
      <%end%>

      <%= link_to anime_path(@animes[5]) do %>
         <div class = "trending-anime-items">
            <div>
               <div class = "trending-anime-posters-wrapper">
                  <%= image_tag "data:image/jpg;base64,#{Base64.encode64(@animes[5].poster).html_safe}", class: "trending-anime-posters" %>
               </div>
               <h2 class = "trending-anime-title"> <%=@animes[5].name %> </h2>
            </div>
            <div class = "trending-anime-release-wrapper">
               <span class = "trending-anime-release"><%=@animes[5].content_type %> / <%=@animes[5].release_date.year %><span>
            </div>
         </div>
      <%end%>

      <%= link_to anime_path(@animes[6]) do %>
         <div class = "trending-anime-items">
            <div>
               <div class = "trending-anime-posters-wrapper">
                  <%= image_tag "data:image/jpg;base64,#{Base64.encode64(@animes[6].poster).html_safe}", class: "trending-anime-posters" %>
               </div>
               <h2 class = "trending-anime-title"> <%=@animes[6].name %> </h2>
            </div>
            <div class = "trending-anime-release-wrapper">
               <span class = "trending-anime-release"><%=@animes[6].content_type %> / <%=@animes[6].release_date.year %><span>
            </div>
         </div>
      <%end%>

   </section>;
</div>

app/views/home_page/index.html.erb
  <section class="home"></section>

  <%= render "main_carousel"%>
  <%= render "trending_grid"%>
  <%= render "recent_anime_list"%>
  <script>
  let nav = document.querySelector("nav");
    window.onscroll = function() {
      if(document.documentElement.scrollTop > 20){
        nav.classList.add("sticky");
      }else {
        nav.classList.remove("sticky");
      }
    }
  </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnimeGems</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <nav class = "header">
    <div class="nav-content">
      <div class="site-logo">
        <%= link_to "Anime Gems", root_path %>  
      </div>

      <form action="/search" method="GET" class = "search-form">
        <input type="text" name="query" placeholder="Пошук аніме за назвою" autocomplete="off" class = "search-input-field">
        <button type="submit" class = "search-button">Пошук</button>
      </form>

      <ul class="nav-links">
        <li><%= link_to "Аніме", animes_path%></li>
        <li><%= link_to "Випадкове аніме", "#", id: "random-anime-link" %></li>
      </ul>
    </div>
  </nav>

  <body>
    <%= yield %>
  </body>
</html>

<script>
  document.addEventListener('DOMContentLoaded', () => {
    const randomAnimeLink = document.getElementById('random-anime-link');
    randomAnimeLink.addEventListener('click', () => {
      const randomIndex = Math.floor(Math.random() * <%= Anime.count %>) + 1;
      const randomUrl = `/animes/${randomIndex}`;
      window.location.href = randomUrl; 
    });
  });
</script>